import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Providers } from "@/providers";
import "@/styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "AI Marketing OS — Marketing Content from One Product",
    template: "%s | AI Marketing OS",
  },
  description:
    "Upload a product. Get descriptions, ads, emails, SEO, and social posts — all generated by AI. The fastest way to launch products.",
  keywords: [
    "AI marketing",
    "product description generator",
    "ecommerce marketing",
    "Shopify AI",
    "content generator",
  ],
  openGraph: {
    title: "AI Marketing OS",
    description:
      "Generate every marketing asset from a single product upload. Start free.",
    url: "https://aimarketingos.com",
    siteName: "AI Marketing OS",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Marketing OS",
    description:
      "Generate every marketing asset from a single product upload.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="canonical" href="https://aimarketingos.com" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("theme");if(!t)return;var r=t==="system"?window.matchMedia("(prefers-color-scheme:dark)").matches?1:0:t==="dark"?1:0:0;r&&document.documentElement.classList.add("dark")}catch(e){}})();`,
          }}
        />
      </head>
      <body className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
